### ISSUE TITLE
Prevent user from reinstalling engine

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1099]
When selecting an installed engine in the engines tab the result looks like this:
![grafik](https://user-images.githubusercontent.com/18488086/29965151-d5f093da-8f0c-11e7-9bcf-3330181bcd5c.png)
Ideally we should either remove the install button or gray it out.

**Comment by plata** [comment]
We need a better method to figure out if an engine is installed to implement this properly.
I see two possibilities:
1. Store this in the `EngineVersionDTO`. Probably not so good because it would be different from the implementation for apps.
2. Have some kind of manager which can be asked about it.

**Comment by madoar** [comment]
I also think a manager would be better for this.
Do you want to write a new issue for the manager? Ideally with a short description what it needs to contain?
