### ISSUE TITLE
fix missing Wine 64bit versions for OSX

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1138]
Many 64bit Wine versions are missing for OSX in <http://phoenicis.playonlinux.com/index.php/wine?os=darwin>.

See also: <https://www.playonmac.com/en/topic-15522.html>

@qparis you're the only one who can fix this

**Comment by madoar** [comment]
I'm still unsure, why we need our own provider for the wine builds.
I think it's better to directly fetch them from their source.
For example we can fetch wine from https://github.com/wine-mirror/wine/releases and wine staging from https://github.com/wine-compholio/wine-staging/releases.

**Comment by qparis** [comment]
This link only provides source, we need to have reliable binaries for our user, which is hard to have

**Comment by madoar** [comment]
Hmmm, can't we also provide code for building wine on the computer of the user?
I mean we have access to the process api, right?

**Comment by qparis** [comment]
You would need a lot of dependency and it would take at least 30 minutes to install wine

**Comment by plata** [comment]
I agree with @qparis. However, this imposes the responsibility on our side to ensure that the Wine versions are really available. Additionally, we should provide the required resources (scripts etc.) to build Wine as described in #1127.

**Comment by Candunc** [comment]
I've had luck installing the Wine Development package from [here](https://dl.winehq.org/wine-builds/macosx/download.html) and copying ```/Wine Devel.app/Contents/Resources/wine/*``` to ```~/Library/PlayOnMac/wine/darwin-amd64/3.2/```. 

Perhaps a solution to this problem is to add a way to extract from this package and copy to the proper directory, and then link it on [this](http://phoenicis.playonlinux.com/index.php/wine?os=darwin) page?

**Comment by plata** [comment]
@Candunc I wasn't aware that this is possible. Do you know if it works for staging as well?

**Comment by Candunc** [comment]
It appears so, the tarballs work just fine so you don't even need to use the installer as well.

**Comment by plata** [comment]
Ok. We should definitely consider this option.

**Comment by plata** [comment]
@Candunc the current PoL/PoM Wine installations have a gecko/mono version set. Any ideas what's the difference for this when using the tarballs?
I'm thinking if it could be possible to provide an alternative Wine download source which uses the tarballs. Would you mind giving it a try (I can give some support of course)?

**Comment by plata** [comment]
I made a JSON file for Phoenicis which uses the builds from WineHQ. Couldn't test so feel free to give it a try: https://github.com/plata/phoenicis-wine-sources

**Comment by plata** [comment]
@atilling the above might be interesting for you as well.

**Comment by samzilverberg** [comment]
@plata i tried your json file, worked :)

anyone who wants to try it, just edit/create file `~/Library/Phoenicis/config.properties` with:
```
webservice.wine.url = https://raw.githubusercontent.com/plata/phoenicis-wine-sources/master/winehq-macosx.json
```
then start the phoenicis app.
if you still dont see new wine versions, close app and remove the cached versions file:
```
rm ~/Library/Phoenicis/engines/wine/availableVersions.json
```

seems to me `https://dl.winehq.org/wine-builds/macosx/pool/` could be used as a simple source (for mac) to be parsed into an `availableVersions.json` file

**Comment by ImperatorS79** [comment]
Could it be possible to do the same for POL4 ?

And I see you do not specified gecko and mono file. Do wine automatically download them ?

**Comment by plata** [comment]
@samzilverberg that's cool. Actually I'm parsing that link to create the file (see [here](https://github.com/plata/phoenicis-wine-sources/blob/master/winehq-macosx.py)).

**Comment by plata** [comment]
@ImperatorS79 I have no idea about POL4. @qparis ?

I'm not really sure about gecko/mono. If you know how I can determine the correct versions, I can update my script accordingly.

Agree to the last point.

**Comment by plata** [comment]
@madoar @qparis what do you think about replacing our builds with the official ones (for OSX) or at least providing Lutris and WineHQ as alternative sources officially (this would also include documenting it)?

**Comment by ImperatorS79** [comment]
@plata Here the official sites->[https://wiki.winehq.org/Gecko](https://wiki.winehq.org/Gecko), [https://wiki.winehq.org/Mono](https://wiki.winehq.org/Mono)

For gecko there is a table for the compatibility.
For mono, over 1.5.6, any version seems to work

Download : 
[http://dl.winehq.org/wine/wine-gecko/](http://dl.winehq.org/wine/wine-gecko/)
[http://dl.winehq.org/wine/wine-mono/](http://dl.winehq.org/wine/wine-mono/)

**Comment by plata** [comment]
I don't think anybody wants to use Wine <=1.9.13 so it should be fine to use the newest version for gecko and mono. Do you agree?

**Comment by ImperatorS79** [comment]
Yes I do

**Comment by plata** [comment]
I have updated my scripts. Can you check if gecko and mono is working?

**Comment by madoar** [comment]
@plata I can't estimate how much work it is, to change our builds to the official ones, do you have an estimation?

I'm in favor of supporting multiple engine sources, i.e. ours, an official wine source and maybe also the ones from lutris.
I think it would be a good idea to provide a small GUI, which enables the user to switch his selected engine source, or maybe to activate multiple sources at the same time (which will require a hint in the gui showing from which source an engine provided).
This GUI should be accessible via the options tab.

About the wine versions:
I think that if we use a gecko and mono version, which is incompatible with wine versions older than 1.9.13, then we should prevent the users from installing said wine versions.
Otherwise we take the risk of users creating new issues, telling us about version incompatibilities between wine and mono/gecko.

**Comment by plata** [comment]
First of all, we can only use the official builds for OSX. But then it's no work, just do what @samzilverberg described.
I can transfer my repository to PhoenicisOrg. Any proposals regarding the name?

**Comment by madoar** [comment]
Just a little brainstorming from my side:

Can we maybe add your build scripts for the wine build lists as JavaScript scripts to our script repository as an additional way to get the available engines?
This would avoid the need to provide static lists on a server.

**Comment by plata** [comment]
Could work maybe, but it's potentially slow.

**Comment by madoar** [comment]
I think this script should be performed in the background at startup.
The created engine list should be cached locally.

To continue with the idea:
A user could then select one or multiple engine fetch scripts he wants to use.
In addition he could even add his own script, if he has his own engine source.

**Comment by plata** [comment]
There's a third one (i.e. what I'm doing right now): run a cron job in Travis every day which updates my GitHub repository.

**Comment by ImperatorS79** [comment]
Since wine versions are out every 2 weeks, running it once a day is too much :-)

**Comment by madoar** [comment]
@ImperatorS79 For wine that may be true, but I think we should provide a solution that works for other types of engines too. Therefore a shorter cycle may be useful.

@plata so basically it's a combination of the two alternatives?^^
It sounds good to me, I think we can let the name remain as it is, maybe remove the phoenicis part, because this should be clear from the organization name.
The only think I would wish for is a description in the README describing:
- what engine sources are provided
- in which files they are provided
- how they are created
- how often they are updated

**Comment by plata** [comment]
@madoar sure. I'm just fixing a bug with gecko/mono, then I will move it.

**Comment by qparis** [comment]
I think we should go for the solution 2. I can provide the server.

However, to ensure we can maintain such a system, we need to build it on top on containerization system, so that it can run out of the box on any server without complicated installation (Or cloud services)

Docker would be really suited for this

**Comment by plata** [comment]
@qparis you cannot run Mac OSX in Docker as far as I know, so how should that work?

**Comment by qparis** [comment]
OSX version of wine can be crossbuilt on linux. We are currently doing that, but the way we are doing it is outdated. 
Wine staging team has developed far better techniques that could be encapsulated in a well shaped docker container

**Comment by plata** [comment]
I see. But what's the advantage to have our own server compared to using Travis or something like that?

**Comment by qparis** [comment]
Faster and more frequent builds basically. Also, having a system that does not depend on Travis is better for an opensource service prospective: anybody can deploy the wine build service on their own machine.

**Comment by plata** [comment]
We should work together with the guy from Lutris. He's currently working on the same thing. However, I believe we have more important stuff to do right now (like releasing alpha).

**Comment by qparis** [comment]
Agreed, but Lutris has no goals for OSX builds AFAIK. 

I think this is something really important if we want to have something decently stable. Current binaries are builds with old versions of libc ; I'm not sure they will work on future linux distros.

**Comment by plata** [comment]
That's true.

Agreed, but currently it works and even if it doesn't we can still fallback to the official builds with https://github.com/PhoenicisOrg/wine-sources.

**Comment by qparis** [comment]
Regarding alpha version, do you see any missing prerequisites?

**Comment by plata** [comment]
No. The 5.0-alpha branches are tested.

**Comment by qparis** [comment]
Then we can announce it on playonlinux.com as a news now.

**Comment by plata** [comment]
Great! Then we can close #1338 if everything there is done.

**Comment by qparis** [comment]
Fixed
