### ISSUE TITLE
Lacking features

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1436]
Hello, currently I'm using POL 4, but I would like to move to Phoenicis, because it has active development and it is more modern, but I miss some features which POL 4 has but Phoenicis doesn't.

1. Create new container without listed app, so something like in POL 4 you could install non-listed app to specific container (prefix) and you should be able to install multiple applications inside one container.

2. Ability to rename container, change Wine version of container.

3. If I select some application from container I would like to be able to change name of it and set default launching parameters.

4. Ability to install components to container like fonts, dotnet, DirectX, etc..

5. Button to open directory of selected container.

6. Ability to generate shortcut of applications in container. I know that I can create shortcut but it is not automated like in POL4, in Phoenecis you have to fill whole form by yourself.

7. In Library applications should be grouped by containers together.

**Comment by plata** [comment]
Hi, first of all welcome to Phoenicis.

Please open one issue for every missing feature (otherwise this is very hard to track for us).

Apart from that, let me comment some of your remarks:
1. You can do this with the custom installers in the apps tab.
2. Why do you want to rename a container? There's already another issue open for changing the Wine version.
3. In your library, right click the app and select "edit".
4. This is possible during app installation from the script. If that's not enough for you, please open a new issue.
5. I don't see why this should be done.

**Comment by plata** [comment]
Closed as we have separate issues.
