### ISSUE TITLE
[French] When installing any app, placeholder are not replaced

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1640]
See the screenshot: 

![Uploading Capture d’écran 2018-12-27 à 00.41.28.png…]()

**Comment by plata** [comment]
Screenshot doesn't work.

**Comment by qparis** [comment]
<img width="1501" alt="capture d ecran 2018-12-27 a 00 41 28" src="https://user-images.githubusercontent.com/373645/50475555-7f45d100-09c5-11e9-996a-03428be3a340.png">

**Comment by plata** [comment]
If you run it in English or a different language, it works?

**Comment by qparis** [comment]
In english, yes

**Comment by qparis** [comment]
In german, it also works

**Comment by plata** [comment]
Can you diff the strings in the different languages? Maybe there's something strange in French.

**Comment by qparis** [comment]
#: phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/UiSetupWizardImplementation.java:151
#, java-format
msgid "Installation wizard for {0}"
msgstr "Assistant d'installation de {0}"

and 

#: phoenicis-scripts/src/main/java/org/phoenicis/scripts/wizard/UiSetupWizardImplementation.java:151
#, java-format
msgid "Installation wizard for {0}"
msgstr "Installationsassistent für {0}"

**Comment by plata** [comment]
Ok...

**Comment by plata** [comment]
I can reproduce this only partly. For example, the script author is replaced for me.
This problem is caused by the single quote (`'`) in `d'installation`. This is not related to the translation at all but is caused by the underlying `MessageFormat.format` (see https://stackoverflow.com/questions/17544794/escaping-single-quotes-for-java-messageformat). As explained in that stack overflow, you can solve the issue by using the correct unicode character instead of a single quote.

**Comment by plata** [comment]
I've changed the translation to use `’` instead of `'` so this should be fixed as soon as we merge the new Crowdin translations.

**Comment by plata** [comment]
Solved.
