### ISSUE TITLE
Local installation: download wine?os=linux, takes time to start

### ISSUE THREAD

**Issue by SanZamoyski** [PhoenicisOrg/phoenicis#1807]
### Expected behavior
Running local installation loads all necessary files fast.

### Actual behavior
Running Local install takes ages to "download wine?os=linux", why is that? (it starts very slowly)

### Steps to reproduce
Run Local installer, select arch and installer file.

### System information
- Version 5.0-alpha-2, GIT revision ends with badce66c (2018.12.31)
- Linux Mint KDE, Linux lati 4.15.5-041505-generic #201802221031 SMP Thu Feb 22 15:32:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux, 18.sth.
- san@lati ~ $ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by plata** [comment]
It is not related to any particular installer. I believe it is something with the server. @qparis any ideas?

**Comment by qparis** [comment]
I am not sure that it comes from the server because the problem does not seem to happen outside phoenicis.

I think it is more a multi threading pool that is full

**Comment by plata** [comment]
How can we figure that out? Maybe the first thing we should do is ensure that a proper message is shown instead of this weird string.

**Comment by qparis** [comment]
I think that if you download a sufficient amount of file in the same time, you'll trigger this problem

**Comment by plata** [comment]
Could you have a look? I'm not quite sure where to start. Also: isn't it just one archive?

**Comment by qparis** [comment]
Merge request #1809 may help to debug

**Comment by Kreyren** [comment]
Same issue here bsaed on #1929  
![image](https://user-images.githubusercontent.com/11302521/56575770-8ae58500-65be-11e9-98e9-e007a34c58c5.png)

**Comment by plata** [comment]
@qparis can you give an example how the thread debugger should be used? Currently, I can't quite figure out what's going on. For example, I've set the size of the scripts thread pool to 1 and it worked without issues. From my understanding, the whole installation should be running in one thread anyways.
Also, the shown download message "wine?os=linux" is created by the downloader: It uses `fetchFileNameFromUrl` with https://phoenicis.playonlinux.com/index.php/wine?os=linux. As the progress text is updated before the download even starts, this issue must arise while fetching the available Wine versions (otherwise the progress text must have changed already).

**Comment by qparis** [comment]
If you run ten scripts at the same time, does the pool works properly?
The debugger should be started in the console. It will display the state of the queue. If one queue remains full, it will highlight a problem

**Comment by plata** [comment]
I've set the number of threads to 2. Trying to run 2 installations in parallel didn't work, i.e. the second started only after the first had finished.

Executing `Bean("controlledThreadPoolExecutorDebugger").start()` in the PlayOnLinux console prints `null` and logs:
```
[    Scripts ] Done:                   11, Running:                    1, Queue:     1 / 50, Avg:      0 t/s, Speed:      0 t/s
```
Looks strange for me because the number of threads is 2, so it should be:
```
[    Scripts ] Done:                   11, Running:                    2, Queue:     0 / 50, Avg:      0 t/s, Speed:      0 t/s
```
Nevertheless, I don't think that this explains this issue.

**Comment by plata** [comment]
**UPDATE**: forget my post above, it works like expected (forget `mvn install` before `mvn exec:java`...). It would be good to log the thread pool size as well.

**Comment by plata** [comment]
Could this be caused by https://github.com/PhoenicisOrg/scripts/blob/fa0eacc623d20d53cbe53144cf0a21212fca9f64/Engines/Wine/Engine/Implementation/script.js#L320 ?

It seems that the `touch` empties the file.

**Comment by plata** [comment]
The `touch` is ok (it detects correctly that the file exists already).

The issue is in the `Downloader`:
1. It does not detect correctly that the file did not change in https://github.com/PhoenicisOrg/scripts/blob/fa0eacc623d20d53cbe53144cf0a21212fca9f64/Utils/Functions/Net/Download/script.js#L128.
2. It downloads directly to the specified location (https://github.com/PhoenicisOrg/scripts/blob/fa0eacc623d20d53cbe53144cf0a21212fca9f64/Utils/Functions/Net/Download/script.js#L137). I'm not sure that's a good idea because it empties the file first. So e.g. if the file cannot be downloaded, you will not be able to continue with the old file.

**Comment by madoar** [comment]
> Apart from this, there must still be an issue in the software: The progress bar is not moving at all at the beginning (not even the mark that something is happening without showing the progress).

Hmm maybe the `_wizard` variable is not set? 

Apart from this I think it would be useful to print the duration needed to execute parts of the code. This should allow us to detect which part is blocking the execution

**Comment by plata** [comment]
The `wizard` is set. It seems that the actual downloading takes time to start.
