### ISSUE TITLE
Breeze Dark: wrong highlight color in repository settings

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1852]
![image](https://user-images.githubusercontent.com/11302521/53238877-d2bd5e00-369a-11e9-94af-eeafd46fa4a1.png)

### System information
* software version (git revision) of phoenicis and scripts repositories
* used operating system - 4.18.0-15-generic (ubuntu 4.18.10)
* used Java version - http://ix.io/1BJM
![image](https://user-images.githubusercontent.com/11302521/53240035-d999a000-369d-11e9-9b18-3868a08123ac.png)

**Comment by plata** [comment]
@madoar is this from your changes?

**Comment by madoar** [comment]
Yes it is. I think all the components will need to be checked. The issue here is, that we didn't use a table previously so we don't have css for it. I can imagine that the verb section in the container panel also looks "broken" with some themes.

I'm not sure if I can fix this alone, because I don't know how the components should look for each skin. Do we have a kind of specification for the themes? If someone wants to help fix the themes, all help is welcome!

**Comment by madoar** [comment]
This is linked to #1800

**Comment by plata** [comment]
There's no specification. For Unity, Mint X and Breeze I just tried to resemble the original as good as possible. In this case, I would say the selection color has to be fixed.
