### ISSUE TITLE
Gitpod doesn't start

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1941]
Gitpod can't be started. When opening https://gitpod.io/#https://github.com/PhoenicisOrg/phoenicis, I get the following error log:

```
...

Stop! java 11.0.2-open is not installed.

Stop! java 11.0.2-open is not installed.

The command '/bin/sh -c bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh && sdk default java 11.0.2-open"' returned a non-zero code: 1
```

**Comment by plata** [comment]
@meysholdt any ideas?

**Comment by meysholdt** [comment]
yes, the java version in the base image changed... find the current ones here:

https://github.com/gitpod-io/workspace-images/blob/43f3eca5d94463903444c70789aaf399cda8255e/full/Dockerfile#L137-L144

Maybe using `sdk default java 11` works, instead of `sdk default java 11.0.2-open`.

Then changes in minor versions won't be breaking.

**Comment by plata** [comment]
Is this something we can configure? If so, how?

**Comment by Kreyren** [comment]
Probably some sanitization for versioning would be required assuming that there is a scenario in which `sdk default java 11.0.2-open` is beeing used when `sdk default java 11` is expected.

**Comment by Kreyren** [comment]
meh

**Comment by meysholdt** [comment]
hey @Kreyren, that doesn't look good. Thank you for recording the video. We'll look into it.

**Comment by meysholdt** [comment]
I've filed https://github.com/gitpod-io/gitpod/issues/585 to track the UI issue.
