### ISSUE TITLE
Abstract: Merge all issues in one single repository.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1948]
As refferenced on https://github.com/PhoenicisOrg/scripts/issues/881#issuecomment-493806021

It's pita to manage issues that are across multiple repositories.. this would be much better if they ware merged into one issue tracker and managed with flags to differenciate. + it would direct focus on issue since some repositories has less attention.

**Comment by plata** [comment]
I do not agree. In many cases (e.g. app wishes), the issues are very different on the repos. Also, it makes no sense to e.g. mix winebuild stuff with scripts.

**Comment by Kreyren** [comment]
> I do not agree. In many cases (e.g. app wishes), the issues are very different on the repos. Also, it makes no sense to e.g. mix winebuild stuff with scripts.

I believe it makes sence assuming it beeing sorted using flags since github issue tracker has filter functionality and made everything available from one single repository to prevent duplicates and make all issues available without wasting time browsing github issues for that specific issue.

**Comment by madoar** [comment]
I also think it is a better idea to split the issues according to their targeted subject. The normal Phoenicis user for example will care nothing about issues with winebuild, because he or she expects a wine build to exist and doesn't care how/where it has been created/built.

The same is basically true for the distinction between the scripts and phoenicis repositories. When a user executes a script and receives a "ScriptError" he will normally search for the reason somewhere in the script repository. Analogous if a user has an issue with the Phoenicis, because a window for example looks strange/bugged he will search for the issue inside the phoenicis repository.

I know that this is an idealized view which is not yet always the case because Phoenicis is still in an alpha release state, but long-term this is where we want to arrive.

**Comment by Kreyren** [comment]
Doubt, but fair enough
