### ISSUE TITLE
Ubuntu 19.10 to drop 32bit x86 packages

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#2012]
It has been announced that Ubuntu will drop support for 32bit x86 packages starting with [19.10](https://lists.ubuntu.com/archives/ubuntu-announce/2019-June/000245.html).
This is currently discussed also on the [WineHQ mailing list](https://www.winehq.org/pipermail/wine-devel/2019-June/147869.html). Apparently, there are considerations to use the [Steam runtime](https://github.com/ValveSoftware/steam-runtime) or provide a runtime like we do. However, we already noticed that some packages do not work in the runtime.
Therefore, I think we should talk about our strategy again and probably also get in touch with the Wine guys.

**Comment by ImperatorS79** [comment]
The best option IMHO is to wait for a compiler which will "convert 32 bits code 64 bits", like the `-mwine32` option of llvm that is worked on by a wine dev, as @qparis talked about in a issue on the winebuild repo.

**Comment by Kreyren** [comment]
phoenicis runtime should work no issue if we adapt it with some logic or force compilation.. 

Waiting for compiler that converts 32 bit into 64 bit is probably insane assuming complexity of these libs.

**Comment by ImperatorS79** [comment]
The biggest problem is to get rid of libc6:i386, which will not be an easy task. There is also the problem with graphics driver for example. I do not think 32 bits apps use 64 bits drivers.

**Comment by Kreyren** [comment]
Why are you suggesting such an insane solution? Removing libs from wine is never a good idea

**Comment by ImperatorS79** [comment]
@Kreyren what are you speaking about ?

**Comment by Kreyren** [comment]
From what i understand you are suggesting waiting for converting 32 bit libs into 64 bit libs which is not acceptable solution which even if it was possible would cause additional issues for the wineapps which would take time to resolve by upstream + **WE CAN NOT DEPRECATE 32-BIT!!** Anti-cheats and lots of wineapps has hard dependency on them, league of legends beeing one of many examples to get past anti-cheat in 9.10.

Just provide a logic to use runtime depending on distro used which is the only option we have.. If you have other solutions then provide them additionally to this one so that we can provide the best compatibility possible depending on wine development.

**Comment by ImperatorS79** [comment]
The option to trunk 32 bits to 64 bits is on the long long term (because one day I am sure every linux distro will drop i386, but in a more intelligent way than ubuntu). On the short term, we definitely can just use a "runtime" logic, but:
- We will be relying on the fact that debian keep building i386 package
- We will have to use patchelf to tell wine binaries (executables and .so) to use our ld-linux.so (its path is hardcoded in the file at compile time).
- We will have to think about i386 graphics drivers, because nobody would want to use debian outdated i386 drivers.

But yeah it would be great if ubuntu did not take this decision and if community could do something about it, but I am not really confident about this.

**Comment by Kreyren** [comment]
>  I am sure every linux distro will drop i386, but in a more intelligent way than ubuntu

Debian nor gentoo won't since they both respect gnu to support everything it's possible that the 32-bit would get less development activity tho.

> We will be relying on the fact that debian keep building i386 package

thank god for that.. What is the issue exactly?

> We will have to use patchelf to tell wine binaries (executables and .so) to use our ld-linux.so (its path is hardcoded in the file at compile time).

We could make logic to use system if sufficient too..

> We will have to think about i386 graphics drivers, because nobody would want to use debian outdated i386 drivers (or use the one from sid maybe ?).

NO! you won't be grabbing things for sid trust me that's the last thing you want.. These are not stable! I would be for compiling them on demand it doesn't need much of the system resources really.. Else Grab then from debian or build them manually to your liking.

> But yeah it would be great if ubuntu did not take this decision and if community could do something about it, but I am not really confident about this.

Just let them suffer :p Funtoo did the same thing and their last release is still broken afaik.. It's just lazy devs doing shitty decisions really..

**Comment by plata** [comment]
> Just let them suffer :p Funtoo did the same thing and their last release is still broken afaik.. It's just lazy devs doing shitty decisions really..

We cannot simply drop support for one of the widest used distros out there...

**Comment by ImperatorS79** [comment]
@plata Will it stays the most used distribution if they continue in that direction ? ^^

**Comment by qparis** [comment]
IMHO, I think that Canonical have all the data to take this decision and it would be a mistake to treat them like fools. 
Their decision doesn't suit us at all, but we (linux users that still need 32bits support)  represent a small percentage of the whole user base. We definitely need to find a solution.

**Comment by ImperatorS79** [comment]
> Their decision doesn't suit us at all, but we (linux users that still need 32bits support) represent a small percentage of the whole user base

It would be interesting to have an actual study about this; what do ubuntu users want ?

**Comment by Kreyren** [comment]
@plata Provide the runtime then.. ideally just allows us to push specified libs using scripts. 

@qparis 
>  I think that Canonical have all the data to take this decision and it would be a mistake to treat them like fools.

it's not Canonical anymore it's dell and dell is doing stupid things all the time :man_shrugging: 

>  represent a small percentage of the whole user base.

everyone matters in linux 

> It would be interesting to have an actual study about this; what do ubuntu users want ?

Afaik most of the ubuntu users doesn't have the mind of it's own they just want everything to work out of the box..

**Comment by qparis** [comment]
@Kreyren Please stop this. Really.

This issue is about getting 32bits apps compatible in future systems (Ubuntu and also macOS by the way), not about complaining or bashing about companies decision. By the way, the thoughs like _everyone matters in linux_ are just short sighted. OS projects and companies do not have infinite manpower. This is just normal to focus first on the tasks that make the majority of people happy. 

Please leave the floor to those who have ideas or solutions for this problem.

**Comment by Kreyren** [comment]
Relevant: https://www.omgubuntu.co.uk/2019/06/steam-announces-that-its-dropping-support-for-ubuntu

Even work for us to make steam working now.. 

--- 

> Please leave the floor to those who have ideas or solutions for this problem.

Wine has hard dependency on 32-bit libs and ubuntu won't provide them.. There isn't really any other way to solve this without making our runtime.. Even if you made 32-bit to be compatible on 64-bit (if it's even possible) as @ImperatorS79 suggested then these would still break compatibility..

Worst case scenario you add 32-bit libs from debian in  `/etc/apt/sources.list`

i woudn't be writing anything here if i didn't have solution or idea to the issue.

**Comment by Kreyren** [comment]
Hiding this so that qparis would hate me less:

<details>
>  OS projects and companies do not have infinite manpower. 

You have infinite man power in FOSS.. I hope that you will understand why am i suggesting respecting GNU ethics.. -> If you don't have sufficient man power -> you adapt the function so that it would be as painless as possible assuming current circumstances for someone else to contribute it.. 

Effectively giving you infinite man power for these who needs said function even when it's agains your abstract.. 
</details>

**Comment by qparis** [comment]
@Kreyren I won't repeat it once again. So please listen *very* carefully. 

You have been warned several times. You have been banned from the community for 3 days before. Your comments are provoking, subject to controversy and most of the time not helpful at all. I'm warning you one very last time. The next comment like this from will lead to a permanant ban.  

You exactly now what I am talking about because you've hidden the message. So next time, I really suggest you not to post it. Find another place to vent your frustration.

**Comment by Kreyren** [comment]
I'm sorry that you find my messages provoking i mean well since i'm using phoenicis and i doubt that you will find any other solution so info provided should be respected. 

I'm not aware of beeing banned and i restricted phoenicis contrib to personal fork.

**Comment by qparis** [comment]
> I'm sorry that you find my messages provoking i mean well since i'm using phoenicis and i doubt that you will find any other solution so info provided should be respected.

The info are fine. I'm talking about you bashing dell, canonical, flatpak, our work, and pretty much everything. Please make the difference between the two kinds of comment and please stay profesional. 
Personal advice:  Be more humble, you have more to learn that you think. You are not always right. Sometimes, you need to learn to keep a low profile. Don't try to always have the last word. 

> I'm not aware of beeing banned and i restricted phoenicis contrib to personal fork.

This is fine.

**Comment by plata** [comment]
I've heard that there might be plans to keep support for a selected set of 32bit libraries. Apart from that, it seems like Valve is moving away from Ubuntu. Let's see how this turns out.

After all, our users on Ubuntu could still use the flatpak I think.

**Comment by ImperatorS79** [comment]
Since their decision did a lot of noise, they have a little bit "roll back" and said they will keep 32 bits libs to their version in 18.04.

From the post I have seen on diverse gaming website, most people are planing to move away from ubuntu (me too)(nothing statistical/scientific here ^^).

But I agree, let's see what will happen. They might roll back even more or change again their decisionn.

**Comment by plata** [comment]
To me it seems that they want to enforce snap. Honestly, I don't think this will work out...

**Comment by ImperatorS79** [comment]
@plata end of drama https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-Partial-32-Bit-19.10.

> Ultimately though they will be pushing for packages like Wine to make use of Snaps or other containers for running 32-bit software in the future.

However I still do not like where it is going for long term ^^.

**Comment by plata** [comment]
I think we can close this for now.

**Comment by Kreyren** [comment]
> Canonical may revert course and provide **limited 32-bit support**.

Notice: **limited 32-bit support**..

Why is making cherrypickable runtime an issue when it's permanent fix to so many issues?
