### ISSUE TITLE
Can we use ES modules instead of custom include system?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#2042]

**Comment by madoar** [comment]
I think we have two requirements to make it work:
- we need to be able to extend the `import` mechanism with our own module-path resolution code
- we need to be able to `import` scripts in an "anonymous" manner so that we can use a part of the script (i.e. classes) without knowing its defined name inside the script

**Comment by madoar** [comment]
@plata I've taken a more detailed look at this. It seems that we may be able to support the ECMAScript `import` mechanism by using the `node` builder instead of the `js` builder.

This should then allow us to use `import` together with ES modules. To extend the loading mechanism with a custom rule resolution we would then need to provide a custom `loader` to `node`. How to write such a loader can be found [here](https://github.com/graalvm/graaljs/blob/master/graal-nodejs/doc/api/esm.md) 

### Open/Unsure points:
- how do we pass the `loader` to the `node` builder?
- how much of the ES Module API is supported by graal.js, when they write on their page:
   >  Not all features of the EP are complete and will be landing as both VM support and implementation is ready. Error messages are still being polished.

**Comment by plata** [comment]
> how do we pass the loader to the node builder?

Is this something we can figure out ourselves or do we have to ask the graal developers?

In general: can Graal run Node embedded or only start apps via the `node` application?

**Comment by madoar** [comment]
> Is this something we can figure out ourselves or do we have to ask the graal developers?

I think we will need to ask the graaljs developers about this. Especially useful in my opinion would be if we can "inject" a custom loader that has been implemented as a Java-class

> In general: can Graal run Node embedded or only start apps via the node application?

I think it can run `node` embedded. This should be easy to test I think. Just change: 

https://github.com/PhoenicisOrg/phoenicis/blob/a3ef62ef7f3b12bbde345eeb86ca5c3946950cf9/phoenicis-scripts/src/main/java/org/phoenicis/scripts/engine/ScriptEngineType.java#L15

to `return new PolyglotScriptEngine("node",`

**Comment by plata** [comment]
What about: https://stackoverflow.com/questions/19903398/node-js-customize-require-function-globally?

**Comment by plata** [comment]
One other thing to consider: If we use a "node" environment, will we enable functionality that we do not want to offer?

**Comment by madoar** [comment]
> What about: https://stackoverflow.com/questions/19903398/node-js-customize-require-function-globally?

This is the older "require" syntax not the ES6 "import/export" syntax. Which one do we want to use longterm?

> One other thing to consider: If we use a "node" environment, will we enable functionality that we do not want to offer?

As long as we can provide our own loading/path resolution mechanism I don't think that we expose functionality that we don't want to

**Comment by plata** [comment]
Probably ES6 syntax. For me it feels strange to use node because it suggests that you can use node modules etc. I don't think we want that.

**Comment by madoar** [comment]
> For me it feels strange to use node because it suggests that you can use node modules etc

If I understand ES6 modules correctly we can disable this by using a custom loader.

**Comment by plata** [comment]
Did you see https://github.com/graalvm/graaljs/issues/92#issuecomment-474864328?

**Comment by madoar** [comment]
No I didn't. So we're unable to provide our own custom loader? Then we can't use ES6 modules.

**Comment by plata** [comment]
I think so, yes.

**Comment by madoar** [comment]
@plata I think we can close this now that we have a more sophisticated module system. What do you think?

**Comment by plata** [comment]
Yes. We should keep it in the back of our heads to really use ES6 modules if it should become possible via custom loaders.
